
let categorieArray =    [["1","truitjes","Truitjes en jassen"],
                        ["2","broeken","Broeken"],
                        ["3","accessoires","Accessoires"]];
let productArray = [
    ["1","Castelli Pro Korte Mouwen Heren (detail)","pr_s_m_cas_1_kl.jpg","100"],
    ["1","Castelli Raddoppia Fietsjack Fluo Geel Heren (detail)","pr_s_m_cas_2_kl.jpg","230"],
    ["1","Sportful Fiandre Pro Korte Mouwen Rood Heren","pr_s_m_sf_1_kl.jpg","210"],
    ["1","Sportful Monocrom Fietsshirt Korte Mouwen Zwart Heren","pr_s_m_sf_2_kl.jpg","70"],
    ["1","Sportful Neo Softshell Fietsjack Rood Zwart Heren","pr_s_m_sf_3_kl.jpg","140"],
    ["1","Rapha WMN Canyon-SRAM Pro Team Aero Jersey (detail)","pr_s_w_canyon_1_kl.jpg","175"],
    ["1","Rapha Women's 100 Core Short Sleeve Jersey","pr_s_w_canyon_3_kl.jpg","70"],
    ["1","Castelli Diagonal FZ Fietsshirt Lange Mouwen Donkergroen-Roze-Geel Dames (detail)","pr_s_w_cas_1_kl.jpg","110"],
    ["1","Sportful Diva Fietsshirt Korte Mouwen Blauw Dames (detail)","pr_s_w_sf_1_kl.jpg","59"],
    ["1","Sportful Oasis Thermal Fietsshirt Lange Mouwen Rood Dames (detail)","pr_s_w_sf_2_kl.jpg","95"],
    ["1","Northwave Origin Fietsshirt Korte Mouwen Junior - Blauw Oranje","pr_s_k_nw_1_kl.jpg","40"],
    ["1","Santini 365 GS Fietsshirt Kid","pr_s_k_sant1_kl.jpg","36"],
    ["1","Sportful Team Junior Jacket - Red","pr_s_k_sf1_kl.jpg","91"],
    ["1","Specialized RBX Comp Logo Team Youth Fietsshirt Korte Mouwen - black-rocket red","pr_s_k_spec1_kl.jpg","46"],
    ["2","Castelli Competizione Fietsbroek Kort Zwart Heren","pr_b_m_cas1.jpg","100"],
    ["2","Castelli Sorpasso Ros Fietsbroek Lang Met Zeem Zwart Heren","pr_b_m_cas2.jpg","170"],
    ["2","Sportful Fiandre Norain 2 Fietsbroek Kort Zwart Heren","pr_b_m_sf1.jpg","110"],
    ["2","Rapha Canyon WMN Sram Pro Team Bibshort","pr_b_w_can_1_kl.jpg","230"],
    ["2","Castelli Velocissima Fietsbroek Lang Met Zeem Zwart Dames","pr_b_w_cas1.jpg","120"],
    ["2","Castelli Fiorita Fietsbroek Kort Zwart Dames","pr_b_w_cas2.jpg","84"],
    ["2","Santini 365 GS Kid Bib-Shorts - nautica","pr_b_k_san.jpg","43"],
    ["2","Specialized RBX Comp Logo Team Youth Short","pr_b_k_spec.jpg","31"],
    ["3","Sportful Fiandre Fietshandschoenen Zwart Unisex","pr_pr_acc1.jpg","95"],
    ["3","Sportful Norain Armwarmers Zwart Unisex","pr_pr_acc2.jpg","35"],
    ["3","Sportful Norain Beenwarmers Zwart Unisex","pr_pr_acc3.jpg","50"],
    ["3","GripGrab Skull Cap Windster Zwart","pr_pr_acc4.jpg","28"],
    ["3","Castelli Pro Thermal Muts Roze Dames","pr_pr_acc5.jpg","25"]
]